############################################################
#                                                          #
# docker-compose.yml for Arancino Ecosystem (Alpine Linux) #
#                                                          #
############################################################

version: '3.7'
services:
  redis-volatile-arancino:
    restart: always
    privileged: true
    image: smartmeio/redis-volatile:6.0.16-alpine
    command: redis-server /etc/redis/redis-volatile.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - "arancino_net"

  redis-persistent-arancino:
    restart: always
    privileged: true
    image: smartmeio/redis-persistent:6.0.16-alpine
    command: redis-server /etc/redis/redis-persistent.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - "redis-data:/var/lib/redis"
    networks:
      - "arancino_net"

  arancino:
    restart: always
    privileged: true
    image: smartmeio/arancino:2.7.3-alpine
    command: /bin/bash -c 'gunicorn -c "/etc/arancino/config/gunicorn.cfg.py" arancino.ArancinoStart:app'
    environment:
      - ARANCINO=/etc/arancino
      - ARANCINOCONF=/etc/arancino/config
      - ARANCINOLOG=/var/log/arancino
      - ARANCINOENV=PROD
      - FLASK_ENV=production
      - EDGEUUID=
    volumes:
      - "arancino_conf:/etc/arancino/config"
      - "arancino_log:/var/log/arancino"
      - "/dev:/dev"
    depends_on:
      - redis-volatile-arancino
      - redis-persistent-arancino
    networks:
      - "arancino_net"

  arancino-transmitter:
    restart: always
    image: smartmeio/arancino-transmitter:1.1.0-alpine
    command: /bin/bash -c 'arancino-transmitter'
    environment:
      - ARANCINO=/etc/arancino
      - ARANCINOCONF=/etc/arancino/config
      - ARANCINOLOG=/var/log/arancino
      - ARANCINOENV=PROD
      - EDGEUUID=
    volumes:
      - "arancino-transmitter_conf:/etc/arancino/config"
      - "arancino-transmitter_log:/var/log/arancino"
    depends_on:
      - redis-volatile-arancino
      - redis-persistent-arancino
    networks:
      - "arancino_net"

  arancino-interface:
    restart: always
    image: smartmeio/arancino-interface:1.1.0-dev.1-alpine
    command: /bin/bash -c '/usr/bin/gunicorn --bind=0.0.0.0:5000 --workers=1 arancino_panel:app'
    
    environment:
      - ARANCINO=/etc/arancino
      - ARANCINOCONF=/etc/arancino/config
      - ARANCINOLOG=/var/log/arancino
      - ARANCINOENV=PROD
      - FLASK_ENV=production
      - FLASK_DEBUG=true
      - EDGEDEPLOY=PAES
      - AOS_ENV=PROD
    volumes:
      - "arancino-interface_conf:/etc/arancino/config"
    depends_on:
      - redis-volatile-arancino
      - redis-persistent-arancino
    ports:
      - 127.0.0.1:${INTPORT}:5000
    networks:
      - "arancino_net"

#  mosquitto:
#    restart: always
#    image: smartmeio/eclipse-mosquitto:1.0.0
#    volumes:
#      - "mosquitto_conf:/mosquitto/config"
#      - "mosquitto_data:/mosquitto/data"
#      - "mosquitto_log:/mosquitto/log"
#    ports:
#      - 127.0.0.1:${MPORT}:1883
#      - 127.0.0.1:${MSPORT}:8883
#      - 127.0.0.1:${MWSPORT}:9001
#    networks:
#      - "arancino_net"

  node-red:
    restart: always
    image: nodered/node-red:2.2.0-14
    volumes:
      - node_red_data:/data
    ports:
      - 127.0.0.1:${REDPORT}:1880
    networks:
      - "arancino_net"

volumes:
  node_red_data:
#  mosquitto_conf:
#  mosquitto_data:
#  mosquitto_log:
  redis-data:
  arancino_conf:
  arancino_log:
  arancino-transmitter_conf:
  arancino-transmitter_log:
  arancino-interface_conf:

networks:
  arancino_net:
    driver: "bridge"
