version: '3.7'
services:
  lrod:
    container_name: lrod
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-lrod.dockerfile
    image: smartmeio/lrod:0.4.17
    command: lightning-rod
    volumes:
      - '/srv/lrod/etc/iotronic:/etc/iotronic'
      - '/srv/lrod/var/log/iotronic:/var/log/iotronic'
      - '/srv/lrod/var/lib/iotronic:/var/lib/iotronic'
    ports:
      - '1474:1474'
    networks:
      - 'default'

networks:
  default:
    name: arancino-network-lrod
    driver: 'bridge'
