version: '3.7'
services:
  lrod:
    container_name: lrod
    restart: always
    build:
      context: ../
      dockerfile: dockerfiles-alpine/Dockerfile-lrod-alpine.dockerfile
    image: smartmeio/lrod:0.4.17-alpine
    command: lightning-rod
    volumes:
      # - '/srv/docker/lrod/etc/iotronic:/etc/iotronic'
      - '/srv/docker/lrod/var/log/iotronic:/var/log/iotronic'
      # - '/srv/docker/lrod/var/lib/iotronic:/var/lib/iotronic'
    ports:
      - '1474:1474'
    networks:
      - 'default'

networks:
  default:
    name: arancino-network
    driver: 'bridge'
